from . import whatsapp_gateway
from . import whatsapp_account
from . import whatsapp_template
from . import whatsapp_message
from . import whatsapp_event
from . import res_partner
from . import res_config_settings
from . import stock_lot_hold_order
from . import sale_order
from . import whatsapp_policy
from . import res_users
from . import whatsapp_ai
